version: '3.8'

services:
  video-rag-app:
    build: .
    container_name: open-vrag-video-rag
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      # Set this to true to run selenium in headless mode inside docker
      - HEADLESS=true
    # Increase shared memory size for Chrome, which can be resource-intensive
    shm_size: '2g'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
